[tools]
chezmoi = "latest"
atuin = "latest"
duckdb = "latest"
fd = "latest"
fzf = "latest"
go = "1.25"
golangci-lint = "v2.6.0"
gopls = "latest"
neovim = "latest"
node = "latest"
npm = "latest"
"npm:pyright" = "latest"
op = "latest"
python = "3.11"
rg = "latest"
uv = "0.5.8"
